parameters:
  AzureSubscription: 'SFA-CDH-Dev/Test (962cae10-2950-412a-93e3-d8ae92b17896)'  
  SetSubscriptionScript: 'https://raw.githubusercontent.com/SkillsFundingAgency/dfc-devops/master/PSScripts/Set-EsfaResourceGroupTags.ps1'  
  EnvironmentTag: 'DEV/Test'
  ParentBusiness: ''
  ServiceOffering: ''
  ResourceGroup: ''
  Location: 'West Europe'
  ArmOutputVariableName: 'ARMOutputs'
  WebAppPrefix: ''
  ArtifactRootDirectory: ''
  PackageFile:  '${{ parameters.ArtifactRootDirectory }}/DFC.ServiceTaxonomy.ApiFunction/DeploymentPackages/DFC.ServiceTaxonomy.ApiFunction.zip'
  ArmTemplateFolder: '${{ parameters.ArtifactRootDirectory }}/DFC.ServiceTaxonomy.ApiFunction/Azure/ArmTemplates/'
  ApimImportScript: '${{ parameters.ArtifactRootDirectory }}/DFC.ServiceTaxonomy.ApiFunction/Azure/Scripts/Import-ApimOpenApiDefinitionFromFile.ps1'
  SharedResourceGroup: ''
  ApimServiceName: ''

steps:
- template: deploy-arm-template.yml
  parameters: 
    AzureSubscription: '${{ parameters.AzureSubscription }}'
    SetSubscriptionScript: '${{ parameters.SetSubscriptionScript }}'
    EnvironmentTag: '${{ parameters.EnvironmentTag }}'
    ParentBusiness: '${{ parameters.ParentBusiness }}'
    ServiceOffering: '${{ parameters.ServiceOffering }}'
    ResourceGroup: '${{ parameters.ResourceGroup }}'
    Location: '${{ parameters.Location }}'
    ArmOutputVariableName: '${{ parameters.ArmOutputVariableName }}'
    ArmTemplateFolder: '${{ parameters.ArmTemplateFolder }}'
    ApimImportScript: '${{ parameters.ApimImportScript }}'

- template: StepTemplates/deploy-azure-function.yml
  parameters:
    FunctionType: 'GetAllSkills'
    WebAppName: '${{ parameters.WebAppPrefix }}-stax-skills-fa'
    AzureSubscription: '${{ parameters.AzureSubscription }}'
    PackageFile: '${{ parameters.PackageFile }}'

- template: StepTemplates/deploy-azure-function.yml
  parameters:
    FunctionType: 'GetAllOccupations'
    WebAppName: '${{ parameters.WebAppPrefix }}-stax-occ-fa'
    AzureSubscription: '${{ parameters.AzureSubscription }}'
    PackageFile: '${{ parameters.PackageFile }}'

- template: StepTemplates/deploy-azure-function.yml
  parameters:
    FunctionType: 'GetAllSkillsForOccupation'
    WebAppName: '${{ parameters.WebAppPrefix }}-stax-skillsocc-fa'
    AzureSubscription: '${{ parameters.AzureSubscription }}'
    PackageFile: '${{ parameters.PackageFile }}'

- template: StepTemplates/deploy-azure-function.yml
  parameters:
    FunctionType: 'GetAllOccupationsForSkill'
    WebAppName: '${{ parameters.WebAppPrefix }}-stax-occskills-fa'
    AzureSubscription: '${{ parameters.AzureSubscription }}'
    PackageFile: '${{ parameters.PackageFile }}'

- template: StepTemplates/deploy-azure-function.yml
  parameters:
    FunctionType: 'GetAlternativeCareersAndSkillsForOccupation'
    WebAppName: '${{ parameters.WebAppPrefix }}-stax-altcar-fa'
    AzureSubscription: '${{ parameters.AzureSubscription }}'
    PackageFile: '${{ parameters.PackageFile }}'
    
- template: StepTemplates/deploy-azure-function.yml
  parameters:
    FunctionType: 'GetSkillsGapForOccupations'
    WebAppName: '${{ parameters.WebAppPrefix }}-stax-skillsgap-fa'
    AzureSubscription: '${{ parameters.AzureSubscription }}'
    PackageFile: '${{ parameters.PackageFile }}'
