parameters:
  AzureSubscription: 'SFA-CDH-Dev/Test (962cae10-2950-412a-93e3-d8ae92b17896)'  
  SetSubscriptionScript: 'https://raw.githubusercontent.com/SkillsFundingAgency/dfc-devops/master/PSScripts/Set-EsfaResourceGroupTags.ps1'  
  PackageFile:  ''
  ArmTemplateFolder: ''
  ApimImportScript: ''
  SpecificationPath: ''
  Location: 'West Europe'
  ArmOutputVariableName: 'ARMOutputs'
  EnvironmentTag: 'DEV/Test'
  ParentBusiness: ''
  ServiceOffering: ''
  ResourceGroup: ''
  WebAppPrefix: ''
  SharedResourceGroup: ''
  ApimServiceName: ''
  FunctionAppDomain: ''

steps:
- template: deploy-arm-template.yml
  parameters: 
    AzureSubscription: '${{ parameters.AzureSubscription }}'
    SetSubscriptionScript: '${{ parameters.SetSubscriptionScript }}'
    EnvironmentTag: '${{ parameters.EnvironmentTag }}'
    ParentBusiness: '${{ parameters.ParentBusiness }}'
    ServiceOffering: '${{ parameters.ServiceOffering }}'
    ResourceGroup: '${{ parameters.ResourceGroup }}'
    Location: '${{ parameters.Location }}'
    ArmOutputVariableName: '${{ parameters.ArmOutputVariableName }}'
    ArmTemplateFolder: '${{ parameters.ArmTemplateFolder }}'

- template: deploy-azure-function.yml
  parameters:
    FunctionType: 'GetAllSkills'
    WebAppName: '${{ parameters.WebAppPrefix }}-stax-skills-fa'
    AzureSubscription: '${{ parameters.AzureSubscription }}'
    SharedResourceGroup: '${{ parameters.SharedResourceGroup }}'
    ApimServiceName: '${{ parameters.ApimServiceName }}'
    ApimImportScript: '${{ parameters.ApimImportScript }}'
    SpecificationPath:  '${{ parameters.SpecificationPath }}'
    FunctionAppDomain: '${{ parameters.FunctionAppDomain }}'
    PackageFile: '${{ parameters.PackageFile }}'
    ResourceGroup: '${{ parameters.ResourceGroup }}'

- template: deploy-azure-function.yml
  parameters:
    FunctionType: 'GetAllOccupations'
    WebAppName: '${{ parameters.WebAppPrefix }}-stax-occ-fa'
    AzureSubscription: '${{ parameters.AzureSubscription }}'
    SharedResourceGroup: '${{ parameters.SharedResourceGroup }}'
    ApimServiceName: '${{ parameters.ApimServiceName }}'
    ApimImportScript: '${{ parameters.ApimImportScript }}'
    SpecificationPath:  '${{ parameters.SpecificationPath }}'
    FunctionAppDomain: '${{ parameters.FunctionAppDomain }}'
    PackageFile: '${{ parameters.PackageFile }}'
    ResourceGroup: '${{ parameters.ResourceGroup }}'

- template: deploy-azure-function.yml
  parameters:
    FunctionType: 'GetAllSkillsForOccupation'
    WebAppName: '${{ parameters.WebAppPrefix }}-stax-skillsocc-fa'
    AzureSubscription: '${{ parameters.AzureSubscription }}'
    SharedResourceGroup: '${{ parameters.SharedResourceGroup }}'
    ApimServiceName: '${{ parameters.ApimServiceName }}'
    ApimImportScript: '${{ parameters.ApimImportScript }}'
    SpecificationPath:  '${{ parameters.SpecificationPath }}'
    FunctionAppDomain: '${{ parameters.FunctionAppDomain }}'
    PackageFile: '${{ parameters.PackageFile }}'
    ResourceGroup: '${{ parameters.ResourceGroup }}'

- template: deploy-azure-function.yml
  parameters:
    FunctionType: 'GetAllOccupationsForSkill'
    WebAppName: '${{ parameters.WebAppPrefix }}-stax-occskills-fa'
    AzureSubscription: '${{ parameters.AzureSubscription }}'
    SharedResourceGroup: '${{ parameters.SharedResourceGroup }}'
    ApimServiceName: '${{ parameters.ApimServiceName }}'
    ApimImportScript: '${{ parameters.ApimImportScript }}'
    SpecificationPath:  '${{ parameters.SpecificationPath }}'
    FunctionAppDomain: '${{ parameters.FunctionAppDomain }}'
    PackageFile: '${{ parameters.PackageFile }}'
    ResourceGroup: '${{ parameters.ResourceGroup }}'

- template: deploy-azure-function.yml
  parameters:
    FunctionType: 'GetAlternativeCareersAndSkillsForOccupation'
    WebAppName: '${{ parameters.WebAppPrefix }}-stax-altcar-fa'
    AzureSubscription: '${{ parameters.AzureSubscription }}'
    SharedResourceGroup: '${{ parameters.SharedResourceGroup }}'
    ApimServiceName: '${{ parameters.ApimServiceName }}'
    ApimImportScript: '${{ parameters.ApimImportScript }}'
    SpecificationPath:  '${{ parameters.SpecificationPath }}'
    FunctionAppDomain: '${{ parameters.FunctionAppDomain }}'
    PackageFile: '${{ parameters.PackageFile }}'
    ResourceGroup: '${{ parameters.ResourceGroup }}'
    
- template: deploy-azure-function.yml
  parameters:
    FunctionType: 'GetSkillsGapForOccupations'
    WebAppName: '${{ parameters.WebAppPrefix }}-stax-skillsgap-fa'
    AzureSubscription: '${{ parameters.AzureSubscription }}'
    SharedResourceGroup: '${{ parameters.SharedResourceGroup }}'
    ApimServiceName: '${{ parameters.ApimServiceName }}'
    ApimImportScript: '${{ parameters.ApimImportScript }}'
    SpecificationPath:  '${{ parameters.SpecificationPath }}'
    FunctionAppDomain: '${{ parameters.FunctionAppDomain }}'
    PackageFile: '${{ parameters.PackageFile }}'
    ResourceGroup: '${{ parameters.ResourceGroup }}'