pr:
- master

resources:
  repositories:
  - repository: self
  - repository: dfc-devops
    type: github
    name: SkillsFundingAgency/dfc-devops
    ref: refs/tags/v1.6.11
    endpoint: 'GitHub (ESFA)'

stages:
- stage: Build
  jobs:
  - template: /AzureDevOpsTemplates/Build/dfc-arm-build.yml@dfc-devops
    parameters:
      ArmTemplateRoot: "${{ variables['Build.SourceDirectory'] }}/Resources/ArmTemplates"

  - job:
    steps:
    - template: /AzureDevOpsTemplates/Build/dfc-dotnetcore-build.yml@dfc-devops
      parameters:
        SolutionBaseName: 'DFC.ServiceTaxonomy.ApiFunction'
        BuildPlatform: 'any cpu'
        BuildConfiguration: 'release'
        PublishWebApp: 'false'
        TestSuffix: 'Tests'

- stage: DeployToDevServiceTaxonomy
  displayName: Deploy to DEV_SERVICETAXONOMY
  variables:
  - group: dfc-stax-shared-dev
  - group: dfc-shared-dev
  jobs:
  - deployment: DeployTemplate
    displayName: "Deploy ARM templates"
    environment: DEV_SERVICETAXONOMY
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@0
            displayName: "Download build artifacts"
            inputs:
              buildType: 'current'
          - template: StepTemplates/deploy-environment.yml
            parameters:
              AzureSubscription: 'SFA-CDH-Dev/Test (962cae10-2950-412a-93e3-d8ae92b17896)'
              EnvironmentTag: 'DEV/Test'
              ParentBusiness: 'National Careers Service'
              ServiceOffering: 'Service Taxonomy'
              ResourceGroup: 'dfc-dev-stax-api-rg'
              Location: 'West Europe'
              ArtifactName: 'DFC.ServiceTaxonomy.ApiFunction'
              SolutionBaseName: 'DFC.ServiceTaxonomy.ApiFunction'
              WebAppPrefix: 'dfc-dev'
              ArtifactRootDirectory: "{{ variables['System.ArtifactsDirectory'] }}/DFC.ServiceTaxonomy.ApiFunction"

