resources:
  repositories:
  - repository: self
  - repository: dfc-devops
    type: github
    name: SkillsFundingAgency/dfc-devops
    ref: refs/tags/v1.10.1
    endpoint: 'GitHub (ESFA)'

pool:
  name: NCS - CI and CD
  demands:
  - msbuild
  - visualstudio

stages:
- stage: Build
  jobs:
    - job:
      displayName: "Build and test application and templates"
      steps:
      - template: /AzureDevOpsTemplates/Build/StepTemplates/dfc-arm-build.yml@dfc-devops
        parameters:
          ArmTemplateRoot: "$(System.DefaultWorkingDirectory)/Resources/ArmTemplates"
          SolutionBaseName: 'DFC.ServiceTaxonomy.ApiFunction'

      - template: /AzureDevOpsTemplates/Build/StepTemplates/dfc-dotnetcore-build.yml@dfc-devops
        parameters:
          SolutionBaseName: 'DFC.ServiceTaxonomy.ApiFunction'
          BuildPlatform: 'any cpu'
          BuildConfiguration: 'release'
          PublishWebApp: true
          TestSuffix: 'Tests'

      - task: PublishPipelineArtifact@1
        displayName: Publish OpenAPI docs to Pipeline Artifact
        inputs:
          targetPath: "$(System.DefaultWorkingDirectory)/DFC.ServiceTaxonomy.ApiFunction/OpenAPIDocs"
          artifactName: DFC.ServiceTaxonomy.ApiFunction.Resources.OpenAPIDocs

      - task: PublishPipelineArtifact@1
        displayName: Publish API import script to Pipeline Artifact
        inputs:
          targetPath: "$(System.DefaultWorkingDirectory)/Resources/Scripts"
          artifactName: DFC.ServiceTaxonomy.ApiFunction.Resources.Scripts

- stage: DeployToDevServiceTaxonomy
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  displayName: Deploy to DEV_SERVICETAXONOMY
  variables:
  - group: dfc-shared-all
  - group: dfc-stax-shared-all
  - group: dfc-shared-dev
  - group: dfc-stax-shared-dev
  - group: dfc-stax-apifunctions-dev
  - group: 'KeyVault - dfc-dev-shared-kv'
  - name: WebAppPrefix
    value: dfc-dev
  jobs:
  - template: JobTemplates/deploy-environment.yml
    parameters:
      AzureSubscription: 'SFA-CDH-Dev/Test (962cae10-2950-412a-93e3-d8ae92b17896)'
      EnvironmentTag: '$(EnvironmentTag)'
      ParentBusiness: '$(ParentBusiness)'
      ServiceOffering: '$(ServiceOffering)'
      ResourceGroup: 'dfc-dev-stax-api-rg'
      PackageFile:  "$(Pipeline.Workspace)/DFC.ServiceTaxonomy.ApiFunction.DeploymentPackages/DFC.ServiceTaxonomy.ApiFunction.zip"
      ArmTemplateFolder: "$(Pipeline.Workspace)/DFC.ServiceTaxonomy.ApiFunction.Resources.ArmTemplates/"
      ApimImportScript: "$(Pipeline.Workspace)/DFC.ServiceTaxonomy.ApiFunction.Resources.Scripts/Import-ApimOpenApiDefinitionFromFile.ps1"
      SpecificationPath: "$(Pipeline.Workspace)/DFC.ServiceTaxonomy.ApiFunction.Resources.OpenApiDocs"
      SharedResourceGroup: 'dfc-dev-shared-rg'
      ApimServiceName: 'dfc-dev-shared-apim'
      FunctionAppDomain: '$(FunctionAppDomain)'
      EnvironmentName: DEV_SERVICETAXONOMY
      # The Apis parameter requires a complex object be passed in,  which requires some odd looking yaml.
      # The top level -`s here defines an array of "something"
      # The inner level -'s defines an array of mappings.
      Apis: 
        -
          - name: GetAllSkills
            azureFunctionName: "${{ variables.WebAppPrefix }}-stax-skills-fa"
          - name: GetAllOccupations
            azureFunctionName: '${{ variables.WebAppPrefix }}-stax-occ-fa'
          - name: GetAllSkillsForOccupation
            azureFunctionName: '${{ variables.WebAppPrefix }}-stax-skillsocc-fa'
        -
          - name: GetOccupationsByLabel
            azureFunctionName: '${{ variables.WebAppPrefix }}-stax-occbylabel-fa'
            # This property makes the generated deployment job for this function depend on the 'GetAllSkills' deployment job generated by it's entry in previous array element
            # This causes the generated deployment job to delay execution until the 'GetAllSkills' deployment job has finished.
            # As you add items to this array, please reference them back to the task in the same place in the previous
            # array element, so it gives us a partitioned deployment window!
            dependsOn: GetAllSkills
          - name: GetOccupationsWithMatchingSkills
            azureFunctionName: '${{ variables.WebAppPrefix }}-stax-occsmatchskills-ai-fa'
            dependsOn: GetAllOccupations
          - name: GetSkillsGapForOccupationAndGivenSkills
            azureFunctionName: '${{ variables.WebAppPrefix }}-stax-sgoccsgskills-fa'
            dependsOn: GetAllSkillsForOccupation

- stage: DeployToSitServiceTaxonomy
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  displayName: Deploy to SIT_SERVICETAXONOMY
  variables:
  - group: dfc-shared-all
  - group: dfc-stax-shared-all
  - group: dfc-shared-sit
  - group: dfc-stax-shared-sit
  - group: dfc-stax-apifunctions-sit
  - group: 'KeyVault - dfc-sit-shared-kv'
  - name: WebAppPrefix
    value: dfc-sit
  jobs:
  - template: JobTemplates/deploy-environment.yml
    parameters:
      AzureSubscription: 'SFA-CDH-Dev/Test (962cae10-2950-412a-93e3-d8ae92b17896)'
      EnvironmentTag: '$(EnvironmentTag)'
      ParentBusiness: '$(ParentBusiness)'
      ServiceOffering: '$(ServiceOffering)'
      ResourceGroup: 'dfc-sit-stax-api-rg'
      PackageFile:  "$(Pipeline.Workspace)/DFC.ServiceTaxonomy.ApiFunction.DeploymentPackages/DFC.ServiceTaxonomy.ApiFunction.zip"
      ArmTemplateFolder: "$(Pipeline.Workspace)/DFC.ServiceTaxonomy.ApiFunction.Resources.ArmTemplates/"
      ApimImportScript: "$(Pipeline.Workspace)/DFC.ServiceTaxonomy.ApiFunction.Resources.Scripts/Import-ApimOpenApiDefinitionFromFile.ps1"
      SpecificationPath: "$(Pipeline.Workspace)/DFC.ServiceTaxonomy.ApiFunction.Resources.OpenApiDocs"
      SharedResourceGroup: 'dfc-sit-shared-rg'
      ApimServiceName: 'dfc-sit-shared-apim'
      FunctionAppDomain: '$(FunctionAppDomain)'
      EnvironmentName: SIT_SERVICETAXONOMY
      # The Apis parameter requires a complex object be passed in,  which requires some odd looking yaml.
      # The top level -`s here defines an array of "something"
      # The inner level -'s defines an array of mappings.
      Apis: 
        -
          - name: GetAllSkills
            azureFunctionName: "${{ variables.WebAppPrefix }}-stax-skills-fa"
          - name: GetAllOccupations
            azureFunctionName: '${{ variables.WebAppPrefix }}-stax-occ-fa'
          - name: GetAllSkillsForOccupation
            azureFunctionName: '${{ variables.WebAppPrefix }}-stax-skillsocc-fa'
        -
          - name: GetOccupationsByLabel
            azureFunctionName: '${{ variables.WebAppPrefix }}-stax-occbylabel-fa'
            # This property makes the generated deployment job for this function depend on the 'GetAllSkills' deployment job generated by it's entry in previous array element
            # This causes the generated deployment job to delay execution until the 'GetAllSkills' deployment job has finished.
            # As you add items to this array, please reference them back to the task in the same place in the previous
            # array element, so it gives us a partitioned deployment window!
            dependsOn: GetAllSkills
          - name: GetOccupationsWithMatchingSkills
            azureFunctionName: '${{ variables.WebAppPrefix }}-stax-occsmatchskills-fa'
            dependsOn: GetAllOccupations
          - name: GetSkillsGapForOccupationAndGivenSkills
            azureFunctionName: '${{ variables.WebAppPrefix }}-stax-sgoccsgskills-fa'
            dependsOn: GetAllSkillsForOccupation